version: "3"

services: 

    httpd:
        build:
            context: ./apache_src/
            dockerfile: ./Dockerfile
        image: myapache
        container_name: apache-server
        ports: 
            - "80:80"
        logging: 
            driver: "json-file"
            options: 
                max-file: "10"
                max-size: "10m"

    tomcat1:
        build:
            context: ./tomcat_src/
            dockerfile: ./Dockerfile
        image: mytomcat
        container_name: tomcat-server1
        ports: 
            - "8080:8080"
            - "8009:8009"  # for sync with apache
        logging: 
            driver: "json-file"
            options: 
                max-file: "10"
                max-size: "10m"

    tomcat2:
        image: mytomcat
        container_name: tomcat-server2
        depends_on:
            - tomcat1
        ports: # May be need to erase 
            - "8180:8080"
            - "8109:8009"  # for sync with apache
        logging: 
            driver: "json-file"
            options: 
                max-file: "10"
                max-size: "10m"
